[project]
name = "SAADA"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-adk>=1.22.1",
    "langchain>=0.1.0",
    "langchain-google-genai>=4.2.0",
    "langchain-openai>=0.0.5",
    "python-dotenv>=1.0.0",
]

